[
    {
        "username":"plato",
        "password":"password"
    },
    {
        "username":"albus",
        "password":"password"
    },
    {
        "username":"mocha",
        "password":"password"
    }
]